sonar.projectKey=randumart-website
sonar.projectName=RandUmart Website
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/*.min.js,**/coverage/**,**/prisma/migrations/**
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
