import { Category, Concern } from './types';

export const categories: Category[] = [
  {
    slug: 'herbal',
    name: 'Herbal',
    emoji: '🌿',
    description: 'Produk herbal alami untuk menjaga kesehatan keluarga.',
    productCount: 85,
    image: 'https://images.pexels.com/photos/4753990/pexels-photo-4753990.jpeg?auto=compress&cs=tinysrgb&w=1200',
    color: '#1E7A53',
    gradient: 'from-emerald-900/90 via-emerald-800/40 to-transparent',
    accent: 'emerald',
  },
  {
    slug: 'beauty',
    name: 'Beauty',
    emoji: '💄',
    description: 'Makeup mewah untuk tampil memukau setiap hari.',
    productCount: 64,
    image: 'https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg?auto=compress&cs=tinysrgb&w=1200',
    color: '#DB2777',
    gradient: 'from-pink-900/90 via-pink-700/40 to-transparent',
    accent: 'pink',
  },
  {
    slug: 'face-care',
    name: 'Face Care',
    emoji: '✨',
    description: 'Skincare premium untuk wajah bersih, cerah, dan sehat.',
    productCount: 52,
    image: 'https://images.pexels.com/photos/3018845/pexels-photo-3018845.jpeg?auto=compress&cs=tinysrgb&w=1200',
    color: '#7C3AED',
    gradient: 'from-violet-900/90 via-violet-700/40 to-transparent',
    accent: 'violet',
  },
  {
    slug: 'body-care',
    name: 'Body Care',
    emoji: '🧴',
    description: 'Body lotion dan perawatan tubuh sensasi spa di rumah.',
    productCount: 48,
    image: 'https://images.pexels.com/photos/4202325/pexels-photo-4202325.jpeg?auto=compress&cs=tinysrgb&w=1200',
    color: '#D97706',
    gradient: 'from-amber-900/90 via-amber-700/40 to-transparent',
    accent: 'amber',
  },
  {
    slug: 'personal-care',
    name: 'Personal Care',
    emoji: '🧼',
    description: 'Kebersihan diri harian dengan bahan lembut dan aman.',
    productCount: 40,
    image: 'https://images.pexels.com/photos/4202924/pexels-photo-4202924.jpeg?auto=compress&cs=tinysrgb&w=1200',
    color: '#0891B2',
    gradient: 'from-cyan-900/90 via-cyan-700/40 to-transparent',
    accent: 'cyan',
  },
  {
    slug: 'baby-kids',
    name: 'Baby & Kids',
    emoji: '👶',
    description: 'Perawatan lembut untuk si kecil yang aman dan sehat.',
    productCount: 32,
    image: 'https://images.pexels.com/photos/3933254/pexels-photo-3933254.jpeg?auto=compress&cs=tinysrgb&w=1200',
    color: '#2563EB',
    gradient: 'from-blue-900/90 via-blue-700/40 to-transparent',
    accent: 'blue',
  },
  {
    slug: 'supplements',
    name: 'Supplements',
    emoji: '💊',
    description: 'Suplemen multivitamin untuk imun tubuh lebih kuat.',
    productCount: 45,
    image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=1200',
    color: '#059669',
    gradient: 'from-teal-900/90 via-teal-700/40 to-transparent',
    accent: 'teal',
  },
  {
    slug: 'healthy-food',
    name: 'Healthy Food',
    emoji: '🍯',
    description: 'Madu, kurma, dan camilan sehat untuk gaya hidup fit.',
    productCount: 28,
    image: 'https://images.pexels.com/photos/56882/honey-sweet-organic-natural-56882.jpeg?auto=compress&cs=tinysrgb&w=1200',
    color: '#EA580C',
    gradient: 'from-orange-900/90 via-orange-700/40 to-transparent',
    accent: 'orange',
  },
  {
    slug: 'home-care',
    name: 'Home Care',
    emoji: '🏠',
    description: 'Pembersih rumah aman biodegradable untuk keluarga.',
    productCount: 22,
    image: 'https://images.pexels.com/photos/4108715/pexels-photo-4108715.jpeg?auto=compress&cs=tinysrgb&w=1200',
    color: '#0D9488',
    gradient: 'from-teal-900/90 via-teal-700/40 to-transparent',
    accent: 'teal',
  },
  {
    slug: 'gift-package',
    name: 'Gift Package',
    emoji: '🎁',
    description: 'Paket hadiah eksklusif untuk orang tercinta.',
    productCount: 18,
    image: 'https://images.pexels.com/photos/6211262/pexels-photo-6211262.jpeg?auto=compress&cs=tinysrgb&w=1200',
    color: '#9333EA',
    gradient: 'from-fuchsia-900/90 via-fuchsia-700/40 to-transparent',
    accent: 'fuchsia',
  },
];

export const concerns: Concern[] = [
  { slug: 'acne', name: 'Acne', emoji: '🎯', color: 'from-rose-500 to-pink-500', image: 'https://images.pexels.com/photos/3784372/pexels-photo-3784372.jpeg?auto=compress&cs=tinysrgb&w=600' },
  { slug: 'brightening', name: 'Brightening', emoji: '✨', color: 'from-amber-400 to-yellow-500', image: 'https://images.pexels.com/photos/3737599/pexels-photo-3737599.jpeg?auto=compress&cs=tinysrgb&w=600' },
  { slug: 'anti-aging', name: 'Anti Aging', emoji: '⏳', color: 'from-violet-500 to-purple-500', image: 'https://images.pexels.com/photos/3784371/pexels-photo-3784371.jpeg?auto=compress&cs=tinysrgb&w=600' },
  { slug: 'hair-care', name: 'Hair Care', emoji: '💇‍♀️', color: 'from-cyan-500 to-blue-500', image: 'https://images.pexels.com/photos/3993449/pexels-photo-3993449.jpeg?auto=compress&cs=tinysrgb&w=600' },
  { slug: 'immunity', name: 'Immunity', emoji: '🛡️', color: 'from-emerald-500 to-green-500', image: 'https://images.pexels.com/photos/3683107/pexels-photo-3683107.jpeg?auto=compress&cs=tinysrgb&w=600' },
  { slug: 'weight-management', name: 'Weight Management', emoji: '⚖️', color: 'from-teal-500 to-cyan-500', image: 'https://images.pexels.com/photos/3768916/pexels-photo-3768916.jpeg?auto=compress&cs=tinysrgb&w=600' },
];

export const navLinks = [
  { label: 'Home', href: '/' },
  { label: 'Products', href: '/products' },
  { label: 'Categories', href: '/#categories', mega: true },
  { label: 'Brand Ambassador', href: '/#ambassador' },
  { label: 'Promo', href: '/#promo' },
  { label: 'Artikel', href: '/#blog' },
  { label: 'Tentang Kami', href: '/#about' },
  { label: 'FAQ', href: '/#faq' },
  { label: 'Contact', href: '/#contact' },
];

export const formatRupiah = (n: number) =>
  'Rp' + n.toLocaleString('id-ID');
